/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AccountService } from "../account.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AccountCreateInput } from "./AccountCreateInput";
import { AccountWhereInput } from "./AccountWhereInput";
import { AccountWhereUniqueInput } from "./AccountWhereUniqueInput";
import { AccountFindManyArgs } from "./AccountFindManyArgs";
import { AccountUpdateInput } from "./AccountUpdateInput";
import { Account } from "./Account";
import { TransactionFindManyArgs } from "../../transaction/base/TransactionFindManyArgs";
import { Transaction } from "../../transaction/base/Transaction";
import { TransactionWhereUniqueInput } from "../../transaction/base/TransactionWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AccountControllerBase {
  constructor(
    protected readonly service: AccountService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Account })
  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: AccountCreateInput): Promise<Account> {
    return await this.service.create({
      data: {
        ...data,

        business: data.business
          ? {
              connect: data.business,
            }
          : undefined,

        clientsAndSuppliers: data.clientsAndSuppliers
          ? {
              connect: data.clientsAndSuppliers,
            }
          : undefined,
      },
      select: {
        accountantClassificationCode: true,
        accountBalanceAtStartOfSegment: true,
        accountBalanceInForeignCurrency: true,
        accountKey: true,
        accountName: true,

        business: {
          select: {
            id: true,
          },
        },

        centerAccount: true,

        clientsAndSuppliers: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        currencyCodeForForeignCurrency: true,
        examinedBalanceCode: true,
        examinedBalanceCodeDescription: true,
        id: true,
        totalCredit: true,
        totalDebit: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Account] })
  @ApiNestedQuery(AccountFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Account[]> {
    const args = plainToClass(AccountFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        accountantClassificationCode: true,
        accountBalanceAtStartOfSegment: true,
        accountBalanceInForeignCurrency: true,
        accountKey: true,
        accountName: true,

        business: {
          select: {
            id: true,
          },
        },

        centerAccount: true,

        clientsAndSuppliers: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        currencyCodeForForeignCurrency: true,
        examinedBalanceCode: true,
        examinedBalanceCodeDescription: true,
        id: true,
        totalCredit: true,
        totalDebit: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Account })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: AccountWhereUniqueInput
  ): Promise<Account | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        accountantClassificationCode: true,
        accountBalanceAtStartOfSegment: true,
        accountBalanceInForeignCurrency: true,
        accountKey: true,
        accountName: true,

        business: {
          select: {
            id: true,
          },
        },

        centerAccount: true,

        clientsAndSuppliers: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        currencyCodeForForeignCurrency: true,
        examinedBalanceCode: true,
        examinedBalanceCodeDescription: true,
        id: true,
        totalCredit: true,
        totalDebit: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Account })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: AccountWhereUniqueInput,
    @common.Body() data: AccountUpdateInput
  ): Promise<Account | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          business: data.business
            ? {
                connect: data.business,
              }
            : undefined,

          clientsAndSuppliers: data.clientsAndSuppliers
            ? {
                connect: data.clientsAndSuppliers,
              }
            : undefined,
        },
        select: {
          accountantClassificationCode: true,
          accountBalanceAtStartOfSegment: true,
          accountBalanceInForeignCurrency: true,
          accountKey: true,
          accountName: true,

          business: {
            select: {
              id: true,
            },
          },

          centerAccount: true,

          clientsAndSuppliers: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          currencyCodeForForeignCurrency: true,
          examinedBalanceCode: true,
          examinedBalanceCodeDescription: true,
          id: true,
          totalCredit: true,
          totalDebit: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Account })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: AccountWhereUniqueInput
  ): Promise<Account | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          accountantClassificationCode: true,
          accountBalanceAtStartOfSegment: true,
          accountBalanceInForeignCurrency: true,
          accountKey: true,
          accountName: true,

          business: {
            select: {
              id: true,
            },
          },

          centerAccount: true,

          clientsAndSuppliers: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          currencyCodeForForeignCurrency: true,
          examinedBalanceCode: true,
          examinedBalanceCodeDescription: true,
          id: true,
          totalCredit: true,
          totalDebit: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/transaction")
  @ApiNestedQuery(TransactionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Transaction",
    action: "read",
    possession: "any",
  })
  async findManyTransaction(
    @common.Req() request: Request,
    @common.Param() params: AccountWhereUniqueInput
  ): Promise<Transaction[]> {
    const query = plainToClass(TransactionFindManyArgs, request.query);
    const results = await this.service.findTransaction(params.id, {
      ...query,
      select: {
        accountInTransaction: {
          select: {
            id: true,
          },
        },

        actionAmount: true,
        actionIndicator: true,
        actionOperation: true,
        counterAccount: true,
        createdAt: true,
        data: true,
        date: true,
        details: true,

        documentDetail: {
          select: {
            id: true,
          },
        },

        entryDate: true,
        foreignCurrencyAmount: true,
        foreignCurrencyCode: true,
        id: true,
        lineNumberInTransaction: true,
        modifiedDate: true,
        portion: true,

        receiptDetail: {
          select: {
            id: true,
          },
        },

        reference: true,
        reference_2: true,
        transactionNumber: true,
        transactionType: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/transaction")
  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "update",
    possession: "any",
  })
  async connectTransaction(
    @common.Param() params: AccountWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transaction: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/transaction")
  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "update",
    possession: "any",
  })
  async updateTransaction(
    @common.Param() params: AccountWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transaction: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/transaction")
  @nestAccessControl.UseRoles({
    resource: "Account",
    action: "update",
    possession: "any",
  })
  async disconnectTransaction(
    @common.Param() params: AccountWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transaction: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
