export const defaultAccountsData = [
  {
    accountKey: "31001",
    accountName: "קופת מזומן",
    accountantClassificationCode: 0,
    accountBalanceAtStartOfSegment: 0,
    examinedBalanceCode: "310",
    examinedBalanceCodeDescription: "קופות",
    totalCredit: 0,
    totalDebit: 0,
  },
  {
    accountKey: "31002",
    accountName: "קופת שקים",
    accountantClassificationCode: 0,
    accountBalanceAtStartOfSegment: 0,
    examinedBalanceCode: "310",
    examinedBalanceCodeDescription: "קופות",
    totalCredit: 0,
    totalDebit: 0,
  },
  {
    accountKey: "60002",
    accountName: "מס עסקאות",
    accountantClassificationCode: 0,
    accountBalanceAtStartOfSegment: 0,
    examinedBalanceCode: "600",
    examinedBalanceCodeDescription: "מוסדות",
    totalCredit: 0,
    totalDebit: 0,
  },
  {
    accountKey: "50001",
    accountName: "הכנסות ממכירות",
    accountantClassificationCode: 0,
    accountBalanceAtStartOfSegment: 0,
    examinedBalanceCode: "310",
    examinedBalanceCodeDescription: "הכנסות",
    totalCredit: 0,
    totalDebit: 0,
  },
];
