import { FieldDefinition } from "src/types";

export const A000Fields: FieldDefinition[] = [
  {
    Field_Id: 1000,
    Field_Name: "קוד רשומה",
    Translation: "Record Code",
    Type: "Str",
    Length: 4,
  },
  {
    Field_Id: 1001,
    Field_Name: "לשימוש עתידי",
    Translation: "For Future Use",
    Type: "Str",
    Length: 5,
  },
  {
    Field_Id: 1002,
    Field_Name: "סך רשומות בקובץ BKMVDATA",
    Translation: "Total Records in BKMVDATA File",
    Type: "Num",
    Length: 15,
  },
  {
    Field_Id: 1003,
    Field_Name: "מספר עוסק מורשה",
    Translation: "Authorized Dealer Number",
    Type: "Num",
    Length: 9,
  },
  {
    Field_Id: 1004,
    Field_Name: "מזהה ראשי",
    Translation: "Primary Identifier",
    Type: "Num",
    Length: 15,
  },
  {
    Field_Id: 1005,
    Field_Name: "קבוע מערכת/גירסת קובץ",
    Translation: "System Constant/File Version",
    Type: "Str",
    Length: 8,
  },
  {
    Field_Id: 1006,
    Field_Name: "מספר רישום התוכנה",
    Translation: "Software Registration Number",
    Type: "Num",
    Length: 8,
  },
  {
    Field_Id: 1007,
    Field_Name: "שם התוכנה",
    Translation: "Software Name",
    Type: "Str",
    Length: 20,
  },
  {
    Field_Id: 1008,
    Field_Name: "מהדורת התוכנה",
    Translation: "Software Version",
    Type: "Str",
    Length: 20,
  },
  {
    Field_Id: 1009,
    Field_Name: 'מספר ע"מ של יצרן התוכנה',
    Translation: "Manufacturer's VAT Number",
    Type: "Num",
    Length: 9,
  },
  {
    Field_Id: 1010,
    Field_Name: "שם יצרן התוכנה",
    Translation: "Manufacturer's Name",
    Type: "Str",
    Length: 20,
  },
  {
    Field_Id: 1011,
    Field_Name: "סוג התוכנה",
    Translation: "Software Type",
    Type: "Num",
    Length: 1,
  },
  {
    Field_Id: 1012,
    Field_Name: "נתיב מיקום שמירת הקבצים",
    Translation: "File Storage Path",
    Type: "Str",
    Length: 50,
  },
  {
    Field_Id: 1013,
    Field_Name: 'סוג הנהח"ש של התוכנה',
    Translation: "Software Income Tax Type",
    Type: "Num",
    Length: 1,
  },
  {
    Field_Id: 1014,
    Field_Name: "איזון חשבונאי נדרש",
    Translation: "Required Accounting Reconciliation",
    Type: "Num",
    Length: 1,
  },
  {
    Field_Id: 1015,
    Field_Name: "מספר חברה ברשם החברות",
    Translation: "Company Registration Number",
    Type: "Num",
    Length: 9,
  },
  {
    Field_Id: 1016,
    Field_Name: "מספר תיק ניכויים",
    Translation: "Collection File Number",
    Type: "Num",
    Length: 9,
  },
  {
    Field_Id: 1017,
    Field_Name: "שטח נתונים עתידי",
    Translation: "Area for Future Data",
    Type: "Str",
    Length: 10,
  },
  {
    Field_Id: 1018,
    Field_Name: "שם העסק",
    Translation: "Business Name",
    Type: "Str",
    Length: 50,
  },
  {
    Field_Id: 1019,
    Field_Name: "מען העסק - רחוב",
    Translation: "Business Address - Street",
    Type: "Str",
    Length: 50,
  },
  {
    Field_Id: 1020,
    Field_Name: "מען העסק - מס בית",
    Translation: "Business Address - House Number",
    Type: "Str",
    Length: 10,
  },
  {
    Field_Id: 1021,
    Field_Name: "מען העסק - עיר",
    Translation: "Business Address - City",
    Type: "Str",
    Length: 30,
  },
  {
    Field_Id: 1022,
    Field_Name: "מען העסק - מיקוד",
    Translation: "Business Address - ZIP Code",
    Type: "Str",
    Length: 8,
  },
  {
    Field_Id: 1023,
    Field_Name: "שנת המס",
    Translation: "Tax Year",
    Type: "Num",
    Length: 4,
  },
  {
    Field_Id: 1024,
    Field_Name: "טווח נתונים - תאריך התחלה/חיתוך",
    Translation: "Data Range - Start/End Date",
    Type: "Num",
    Length: 8,
  },
  {
    Field_Id: 1025,
    Field_Name: "טווח נתונים - תאריך סיום/חיתוך",
    Translation: "Data Range - End Date",
    Type: "Num",
    Length: 8,
  },
  {
    Field_Id: 1026,
    Field_Name: "תאריך תחילת התהליך",
    Translation: "Process Start Date",
    Type: "Num",
    Length: 8,
  },
  {
    Field_Id: 1027,
    Field_Name: "שעת התחלת התהליך",
    Translation: "Process Start Time",
    Type: "Num",
    Length: 4,
  },
  {
    Field_Id: 1028,
    Field_Name: "קוד שפה",
    Translation: "Language Code",
    Type: "Num",
    Length: 1,
  },
  {
    Field_Id: 1029,
    Field_Name: "סט תוים",
    Translation: "Character Set",
    Type: "Num",
    Length: 1,
  },
  {
    Field_Id: 1030,
    Field_Name: "שם תוכנת הכיווץ",
    Translation: "Compression Software Name",
    Type: "Str",
    Length: 20,
  },
  {
    Field_Id: 1032,
    Field_Name: "מטבע מוביל",
    Translation: "Leading Currency",
    Type: "Str",
    Length: 3,
  },
  {
    Field_Id: 1034,
    Field_Name: "מידע על סניפים/ענפים",
    Translation: "Branch/Division Information",
    Type: "Num",
    Length: 1,
  },
  {
    Field_Id: 1035,
    Field_Name: "שטח לנתונים עתידיים",
    Translation: "Area for Future Data",
    Type: "Str",
    Length: 46,
  },
];
