import { FieldDefinition } from "src/types";

export const B110Fields: FieldDefinition[] = [
  {
    Field_Id: 1400,
    Field_Name: "קוד רשומה",
    Translation: "Record Code",
    Type: "Str",
    Length: 4,
  },
  {
    Field_Id: 1401,
    Field_Name: "מס רשומה בקובץ",
    Translation: "File Record Number",
    Type: "Num",
    Length: 9,
  },
  {
    Field_Id: 1402,
    Field_Name: "מס עוסק מורשה",
    Translation: "Authorized Business Number",
    Type: "Num",
    Length: 9,
  },
  {
    Field_Id: 1403,
    Field_Name: "מפתח החשבון",
    Translation: "Account Key",
    Type: "Str",
    Length: 15,
  },
  {
    Field_Id: 1404,
    Field_Name: "שם החשבון",
    Translation: "Account Name",
    Type: "Str",
    Length: 50,
  },
  {
    Field_Id: 1405,
    Field_Name: "קוד מאזן בוחן",
    Translation: "Examined Balance Code",
    Type: "Str",
    Length: 15,
  },
  {
    Field_Id: 1406,
    Field_Name: "תיאור קוד מאזן בוחן",
    Translation: "Examined Balance Code Description",
    Type: "Str",
    Length: 30,
  },
  {
    Field_Id: 1407,
    Field_Name: "מען הלקוח/ספק - רחוב",
    Translation: "Customer/Supplier Address - Street",
    Type: "Str",
    Length: 50,
  },
  {
    Field_Id: 1408,
    Field_Name: "מען הלקוח/ספק - מספר בית",
    Translation: "Customer/Supplier Address - House Number",
    Type: "Str",
    Length: 10,
  },
  {
    Field_Id: 1409,
    Field_Name: "מען הלקוח/ספק - עיר",
    Translation: "Customer/Supplier Address - City",
    Type: "Str",
    Length: 30,
  },
  {
    Field_Id: 1410,
    Field_Name: "מען הלקוח/ספק - מיקוד",
    Translation: "Customer/Supplier Address - Postal Code",
    Type: "Str",
    Length: 8,
  },
  {
    Field_Id: 1411,
    Field_Name: "מען הלקוח/ספק - מדינה",
    Translation: "Customer/Supplier Address - Country",
    Type: "Str",
    Length: 30,
  },
  {
    Field_Id: 1412,
    Field_Name: "קוד מדינה",
    Translation: "Country Code",
    Type: "Str",
    Length: 2,
  },
  {
    Field_Id: 1413,
    Field_Name: "חשבון מרכז",
    Translation: "Center Account",
    Type: "Str",
    Length: 15,
  },
  {
    Field_Id: 1414,
    Field_Name: "יתרת החשבון בתחילת החתך",
    Translation: "Account Balance at Start of Segment",
    Type: "Num",
    Length: 15,
  },
  {
    Field_Id: 1415,
    Field_Name: 'סה"כ חובה',
    Translation: "Total Debit",
    Type: "Num",
    Length: 15,
  },
  {
    Field_Id: 1416,
    Field_Name: 'סה"כ זכות',
    Translation: "Total Credit",
    Type: "Num",
    Length: 15,
  },
  {
    Field_Id: 1417,
    Field_Name: "קוד בסיווג החשבונאי",
    Translation: "Accountant Classification Code",
    Type: "Num",
    Length: 4,
  },
  {
    Field_Id: 1419,
    Field_Name: "מספר עוסק של ספק/לקוח",
    Translation: "Supplier/Customer Business Number",
    Type: "Num",
    Length: 9,
  },
  {
    Field_Id: 1421,
    Field_Name: "מזהה סניף/ענף",
    Translation: "Branch/Branch Identifier",
    Type: "Str",
    Length: 7,
  },
  {
    Field_Id: 1422,
    Field_Name: 'יתרת חשבון בתחילת חתך במט"ח',
    Translation: "Account Balance in Foreign Currency",
    Type: "Num",
    Length: 15,
  },
  {
    Field_Id: 1423,
    Field_Name: 'קוד מטבע יתרת החשבון בתחילת חתך במט"ח',
    Translation: "Currency Code for Foreign Currency",
    Type: "Str",
    Length: 3,
  },
  {
    Field_Id: 1424,
    Field_Name: "שטח לנתונים עתידיים",
    Translation: "Space for Future Data",
    Type: "Str",
    Length: 16,
  },
];
