import { FieldDefinition } from "src/types";

export const D120Fields: FieldDefinition[] = [
  {
    Field_Id: 1300,
    Field_Name: "קוד רשומה",
    Translation: "Record Code",
    Type: "Str",
    Length: 4,
  },
  {
    Field_Id: 1301,
    Field_Name: "מס רשומה בקובץ",
    Translation: "File Record Number",
    Type: "Num",
    Length: 9,
  },
  {
    Field_Id: 1302,
    Field_Name: "מס עוסק מורשה",
    Translation: "Authorized Business Number",
    Type: "Num",
    Length: 9,
  },
  {
    Field_Id: 1303,
    Field_Name: "סוג מסמך",
    Translation: "Document Type",
    Type: "Num",
    Length: 3,
  },
  {
    Field_Id: 1304,
    Field_Name: "מספר מסמך",
    Translation: "Document Number",
    Type: "Str",
    Length: 20,
  },
  {
    Field_Id: 1305,
    Field_Name: "מספר שורה במסמך",
    Translation: "Line Number in Document",
    Type: "Num",
    Length: 4,
  },
  {
    Field_Id: 1306,
    Field_Name: "סוג אמצעי התשלום",
    Translation: "Payment Method Type",
    Type: "Num",
    Length: 1,
  },
  {
    Field_Id: 1307,
    Field_Name: "מספר הבנק",
    Translation: "Bank Number",
    Type: "Num",
    Length: 10,
  },
  {
    Field_Id: 1308,
    Field_Name: "מספר הסניף",
    Translation: "Branch Number",
    Type: "Num",
    Length: 10,
  },
  {
    Field_Id: 1309,
    Field_Name: "מספר חשבון",
    Translation: "Account Number",
    Type: "Num",
    Length: 15,
  },
  {
    Field_Id: 1310,
    Field_Name: "מספר המחאה",
    Translation: "Check Number",
    Type: "Num",
    Length: 10,
  },
  {
    Field_Id: 1311,
    Field_Name: "תאריך הפירעון של ההמחאה / התשלום",
    Translation: "Payment/Check Clearance Date",
    Type: "Num",
    Length: 8,
  },
  {
    Field_Id: 1312,
    Field_Name: "סכום השורה",
    Translation: "Line Amount",
    Type: "Num",
    Length: 15,
  },
  {
    Field_Id: 1313,
    Field_Name: "קוד החברה הסולקת",
    Translation: "Payee Company Code",
    Type: "Num",
    Length: 1,
  },
  {
    Field_Id: 1314,
    Field_Name: "שם הכרטיס הנסלק",
    Translation: "Swiped Card Name",
    Type: "Str",
    Length: 20,
  },
  {
    Field_Id: 1315,
    Field_Name: "סוג עסקת האשראי",
    Translation: "Credit Transaction Type",
    Type: "Num",
    Length: 1,
  },
  {
    Field_Id: 1320,
    Field_Name: "מזהה סניף/ענף",
    Translation: "Branch/Branch Identifier",
    Type: "Str",
    Length: 7,
  },
  {
    Field_Id: 1322,
    Field_Name: "תאריך המסמך",
    Translation: "Document Date",
    Type: "Num",
    Length: 8,
  },
  {
    Field_Id: 1323,
    Field_Name: "שדה מקשר לכותרת",
    Translation: "Title-Related Field",
    Type: "Num",
    Length: 7,
  },
  {
    Field_Id: 1324,
    Field_Name: "שטח לנתונים עתידיים",
    Translation: "Future Data Area",
    Type: "Str",
    Length: 60,
  },
];
