import { FieldDefinition } from "src/types";

export const M100Fields: FieldDefinition[] = [
  {
    Field_Id: 1450,
    Field_Name: "קוד רשומה",
    Translation: "Record Code",
    Type: "Str",
    Length: 4,
  },
  {
    Field_Id: 1451,
    Field_Name: "מס רשומה בקובץ",
    Translation: "File Record Number",
    Type: "Num",
    Length: 9,
  },
  {
    Field_Id: 1452,
    Field_Name: "מס עוסק מורשה",
    Translation: "Authorized Business Number",
    Type: "Num",
    Length: 9,
  },
  {
    Field_Id: 1453,
    Field_Name: 'מק"ט פריט אוניברסלי',
    Translation: "Universal Item Code",
    Type: "Str",
    Length: 20,
  },
  {
    Field_Id: 1454,
    Field_Name: 'מק"ט הספק/יצרן ( במסמכי רכש )',
    Translation: "Supplier/Manufacturer Item Code (in Purchase Documents)",
    Type: "Str",
    Length: 20,
  },
  {
    Field_Id: 1455,
    Field_Name: 'מק"ט פנימי',
    Translation: "Internal Item Code",
    Type: "Str",
    Length: 20,
  },
  {
    Field_Id: 1456,
    Field_Name: "שם פריט",
    Translation: "Item Name",
    Type: "Str",
    Length: 50,
  },
  {
    Field_Id: 1457,
    Field_Name: "קוד מיון",
    Translation: "Sorting Code",
    Type: "Str",
    Length: 10,
  },
  {
    Field_Id: 1458,
    Field_Name: "תיאור קוד מיון",
    Translation: "Sorting Code Description",
    Type: "Str",
    Length: 30,
  },
  {
    Field_Id: 1459,
    Field_Name: "תיאור יחידת מידה",
    Translation: "Measurement Unit Description",
    Type: "Str",
    Length: 20,
  },
  {
    Field_Id: 1460,
    Field_Name: "יתרת הפריט לתחילת החתך",
    Translation: "Item Balance at the Beginning of the Cut",
    Type: "Num",
    Length: 12,
  },
  {
    Field_Id: 1461,
    Field_Name: "סך הכל כניסות",
    Translation: "Total Inflows",
    Type: "Num",
    Length: 12,
  },
  {
    Field_Id: 1462,
    Field_Name: "סך הכל יציאות",
    Translation: "Total Outflows",
    Type: "Num",
    Length: 12,
  },
  {
    Field_Id: 1463,
    Field_Name: "מחיר עלות במלאי לסוף תקופת החתך מחוץ למחסני ערובה",
    Translation: "Cost Price in Inventory at the End of the Cut Outside Bonded Warehouses",
    Type: "Num",
    Length: 10,
  },
  {
    Field_Id: 1464,
    Field_Name: "מחיר עלות במלאי לסוף תקופת החתך במחסני ערובה",
    Translation: "Cost Price in Inventory at the End of the Cut in Bonded Warehouses",
    Type: "Num",
    Length: 10,
  },
  {
    Field_Id: 1465,
    Field_Name: "שטח לנתונים עתידיים",
    Translation: "Future Data Area",
    Type: "Str",
    Length: 50,
  },
];
