/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DocumentDetailService } from "../documentDetail.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DocumentDetailCreateInput } from "./DocumentDetailCreateInput";
import { DocumentDetailWhereInput } from "./DocumentDetailWhereInput";
import { DocumentDetailWhereUniqueInput } from "./DocumentDetailWhereUniqueInput";
import { DocumentDetailFindManyArgs } from "./DocumentDetailFindManyArgs";
import { DocumentDetailUpdateInput } from "./DocumentDetailUpdateInput";
import { DocumentDetail } from "./DocumentDetail";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DocumentDetailControllerBase {
  constructor(
    protected readonly service: DocumentDetailService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DocumentDetail })
  @nestAccessControl.UseRoles({
    resource: "DocumentDetail",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: DocumentDetailCreateInput
  ): Promise<DocumentDetail> {
    return await this.service.create({
      data: {
        ...data,

        document: data.document
          ? {
              connect: data.document,
            }
          : undefined,

        item: data.item
          ? {
              connect: data.item,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        document: {
          select: {
            id: true,
          },
        },

        id: true,

        item: {
          select: {
            id: true,
          },
        },

        priceWithoutVat: true,
        quantity: true,
        transactionType: true,
        updatedAt: true,
        vatRate: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DocumentDetail] })
  @ApiNestedQuery(DocumentDetailFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DocumentDetail",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<DocumentDetail[]> {
    const args = plainToClass(DocumentDetailFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,

        document: {
          select: {
            id: true,
          },
        },

        id: true,

        item: {
          select: {
            id: true,
          },
        },

        priceWithoutVat: true,
        quantity: true,
        transactionType: true,
        updatedAt: true,
        vatRate: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DocumentDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DocumentDetail",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: DocumentDetailWhereUniqueInput
  ): Promise<DocumentDetail | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,

        document: {
          select: {
            id: true,
          },
        },

        id: true,

        item: {
          select: {
            id: true,
          },
        },

        priceWithoutVat: true,
        quantity: true,
        transactionType: true,
        updatedAt: true,
        vatRate: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DocumentDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DocumentDetail",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: DocumentDetailWhereUniqueInput,
    @common.Body() data: DocumentDetailUpdateInput
  ): Promise<DocumentDetail | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          document: data.document
            ? {
                connect: data.document,
              }
            : undefined,

          item: data.item
            ? {
                connect: data.item,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          document: {
            select: {
              id: true,
            },
          },

          id: true,

          item: {
            select: {
              id: true,
            },
          },

          priceWithoutVat: true,
          quantity: true,
          transactionType: true,
          updatedAt: true,
          vatRate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DocumentDetail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DocumentDetail",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: DocumentDetailWhereUniqueInput
  ): Promise<DocumentDetail | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,

          document: {
            select: {
              id: true,
            },
          },

          id: true,

          item: {
            select: {
              id: true,
            },
          },

          priceWithoutVat: true,
          quantity: true,
          transactionType: true,
          updatedAt: true,
          vatRate: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
