/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteBankbookArgs } from "./DeleteBankbookArgs";
import { BankbookCountArgs } from "./BankbookCountArgs";
import { BankbookFindManyArgs } from "./BankbookFindManyArgs";
import { BankbookFindUniqueArgs } from "./BankbookFindUniqueArgs";
import { Bankbook } from "./Bankbook";
import { BankbookService } from "../bankbook.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Bankbook)
export class BankbookResolverBase {
  constructor(
    protected readonly service: BankbookService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Bankbook",
    action: "read",
    possession: "any",
  })
  async _bankbooksMeta(
    @graphql.Args() args: BankbookCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Bankbook])
  @nestAccessControl.UseRoles({
    resource: "Bankbook",
    action: "read",
    possession: "any",
  })
  async bankbooks(
    @graphql.Args() args: BankbookFindManyArgs
  ): Promise<Bankbook[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Bankbook, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Bankbook",
    action: "read",
    possession: "own",
  })
  async bankbook(
    @graphql.Args() args: BankbookFindUniqueArgs
  ): Promise<Bankbook | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Bankbook)
  @nestAccessControl.UseRoles({
    resource: "Bankbook",
    action: "delete",
    possession: "any",
  })
  async deleteBankbook(
    @graphql.Args() args: DeleteBankbookArgs
  ): Promise<Bankbook | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
